In [ ]:
import numpy as np  # NumPy kütüphanesini np olarak import ediyoruz

# Bir NumPy dizisi oluşturuyoruz ve yazdırıyoruz
print(np.array([2, 4, 6, 8, 10, 12]))

# Başka bir NumPy dizisi oluşturuyoruz
k = np.array([1, 2, 3, 4, 5, 6])
# Dizinin tipini kontrol ediyoruz
type(k)
# Diziyi yazdırıyoruz
print("\n", k)

# 5 elemanlı, elemanları sıfır olan bir NumPy dizisi oluşturuyoruz
np.zeros(5, dtype=np.float32)
# Yukarıdaki diziyi değişkene atayıp yazdırıyoruz
b = np.zeros(5, dtype=np.float32)
print("\n", b)

# 4 elemanlı, elemanları bir olan bir NumPy dizisi oluşturuyoruz ve yazdırıyoruz
print("\n", np.ones(4, dtype=int))

# 2x4 boyutlarında, elemanları bir olan bir NumPy dizisi oluşturuyoruz ve yazdırıyoruz
print("\n", np.ones((2, 4), dtype=int))

# 2x4 boyutlarında, tüm elemanları 6 olan bir NumPy dizisi oluşturuyoruz ve yazdırıyoruz
c = np.full((2, 4), 6)
print("\n", c)

# 22'den başlayarak 66'ya kadar (66 hariç) 4 artarak giden bir NumPy dizisi oluşturuyoruz ve yazdırıyoruz
print(np.arange(22, 66, 4))

# 0 ile 2 arasında (2 dahil) 20 eşit parça oluşturarak bir NumPy dizisi oluşturuyoruz ve yazdırıyoruz
print("\n",np.linspace(0, 2, 20))

# 2 ile 12 arasında (12 hariç) rastgele tam sayılar içeren 3x3 boyutlarında bir NumPy dizisi oluşturuyoruz ve yazdırıyoruz
print("\n",np.random.randint(2, 12, (3, 3)))

# Ortalaması 14 ve standart sapması 5 olan normal dağılımdan rastgele sayılar içeren 4x4 boyutlarında bir NumPy dizisi oluşturuyoruz ve yazdırıyoruz
print("\n",np.random.normal(14, 5, (4, 4)))





[ 2  4  6  8 10 12]

 [1 2 3 4 5 6]

 [0. 0. 0. 0. 0.]

 [1 1 1 1]

 [[1 1 1 1]
 [1 1 1 1]]

 [[6 6 6 6]
 [6 6 6 6]]
[22 26 30 34 38 42 46 50 54 58 62]

 [0.         0.10526316 0.21052632 0.31578947 0.42105263 0.52631579
 0.63157895 0.73684211 0.84210526 0.94736842 1.05263158 1.15789474
 1.26315789 1.36842105 1.47368421 1.57894737 1.68421053 1.78947368
 1.89473684 2.        ]

 [[ 5 10  7]
 [ 2  9  3]
 [ 9  4 11]]

 [[11.17668741 14.34362263 12.13063064 16.54509733]
 [10.67136261 18.92401579 10.27342622  6.52214132]
 [18.70672871 13.3930221  18.93372954 11.75873481]
 [ 6.12320471 16.42306627 -0.32723465 12.52756811]]


In [ ]:
# Bir NumPy dizisi oluşturuyoruz
a = np.array([7, 8, 9, 10, 11, 12, 13])

# Dizinin kaç boyutlu olduğunu yazdırıyoruz
print(a.ndim)  # ndim, dizinin boyut sayısını döndürür. Bu dizi tek boyutludur (vektördür).

# Dizinin şeklini (boyutlarını) yazdırıyoruz
print("\n", a.shape)  # shape, dizinin her boyuttaki eleman sayısını döndürür. Bu dizi 1 boyutlu ve 7 elemanlıdır.

# Dizinin toplam eleman sayısını yazdırıyoruz
print("\n", a.size)  # size, dizideki toplam eleman sayısını döndürür. Bu dizide 7 eleman vardır.


1

 (7,)

 7


In [ ]:
# 1. Tek boyutlu diziler oluşturuluyor
m = np.array([4, 5, 6, 7])
n = np.array([1, 2, 3, 5])

# 2. axis parametresi verilmezse, varsayılan olarak axis=0 kullanılır
result = np.concatenate([m, n])
print(result)
# Açıklama: Bu satırda, m ve n tek boyutlu dizileri concatenate fonksiyonu kullanılarak birleştiriliyor.
# Sonuç, [4 5 6 7 1 2 3 5] şeklinde olur ve diziler birbirinin ardına eklenmiş olur.

# 3. İki boyutlu diziler oluşturuluyor
m = np.array([[4, 5, 6, 7]])
n = np.array([[1, 2, 3, 5]])

# 4. axis=0 parametresi ile iki boyutlu diziler birleştiriliyor
result = np.concatenate([m, n], axis=0)
print("\n", result)
# Açıklama: Bu satırda, m ve n iki boyutlu dizileri (her biri tek bir satır içeriyor) concatenate fonksiyonu ile axis=0
# (yani dikey eksen) üzerinde birleştiriliyor. Sonuç, alt alta eklenmiş iki boyutlu bir dizi olur:
# [[4 5 6 7]
#  [1 2 3 5]]

# 5. İki boyutlu diziler oluşturuluyor (tekrar)
m = np.array([[4, 5, 6, 7]])
n = np.array([[1, 2, 3, 5]])

# 6. axis=1 parametresi ile iki boyutlu diziler birleştiriliyor
result = np.concatenate([m, n], axis=1)
print("\n", result)
# Açıklama: Bu satırda, m ve n iki boyutlu dizileri concatenate fonksiyonu ile axis=1 (yani yatay eksen) üzerinde
# birleştiriliyor. Sonuç, yan yana eklenmiş iki boyutlu bir dizi olur:
# [[4 5 6 7 1 2 3 5]]



[4 5 6 7 1 2 3 5]

 [[4 5 6 7]
 [1 2 3 5]]

 [[4 5 6 7 1 2 3 5]]


In [ ]:

# Orijinal dizi oluşturuluyor
s = np.array([4, 7, 8, 12, 3, 6, 14, 24, 20, 18])

# Diziyi sıralama
sorted_s = np.sort(s)

print(sorted_s)



[ 3  4  6  7  8 12 14 18 20 24]


In [ ]:

# 1. Normal dağılımdan rastgele sayılar üretme
l = np.random.normal(10, 3, (2, 2))
print(l)

# 2. Diziyi sıralama
print("\n", np.sort(l))


[[ 8.31307908 11.53046769]
 [13.76252739 12.65167666]]

 [[ 8.31307908 11.53046769]
 [12.65167666 13.76252739]]


In [ ]:
# Bir numpy dizisi oluşturuluyor
x = np.array([7, 8, 9, 12, 14, 17, 6, 5, 3])

# Dizinin ilk elemanına erişme
print(x[0])

7


In [ ]:
x[-1] # Dizinin son elemanına erişim


3

In [ ]:
x[3] # Dizinin 4. elemanına erişim

12

In [ ]:
y = np.array([[1,2,3,4],
             [5,6,7,8]])

y[1,1]

6

In [ ]:
y[:,1]

array([2, 6])

In [ ]:
x = np.arange(35, 75)
x

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74])

In [ ]:
x[0:6]

array([35, 36, 37, 38, 39, 40])

In [ ]:
x[:5]

array([35, 36, 37, 38, 39])

In [ ]:
x[34:]

array([69, 70, 71, 72, 73, 74])

In [ ]:
x[4::4]

array([39, 43, 47, 51, 55, 59, 63, 67, 71])

In [ ]:
x[0::4]

array([35, 39, 43, 47, 51, 55, 59, 63, 67, 71])

In [ ]:
y = np.random.randint(5, size =(3,3))
y

array([[3, 0, 0],
       [0, 0, 1],
       [2, 4, 1]])

In [ ]:
y[:,2]

array([0, 1, 1])

In [ ]:
y[0]

array([3, 0, 0])

In [ ]:
y[1,:]

array([0, 0, 1])

In [ ]:
y[:,0:2]

array([[3, 0],
       [0, 0],
       [2, 4]])

In [ ]:
y

array([[3, 0, 0],
       [0, 0, 1],
       [2, 4, 1]])

In [ ]:
y[0:2, 1:3]

array([[0, 0],
       [0, 1]])

In [ ]:
a = np.random.randint(15, size = (5,5))
a

array([[10, 10,  4,  1,  6],
       [ 6,  6, 11,  0, 11],
       [ 6,  6, 12,  8, 11],
       [ 7, 12, 12, 10, 11],
       [10, 10,  6,  3,  5]])

In [ ]:
alt_a = a[0:2, 0:2]
alt_a

array([[10, 10],
       [ 6,  6]])

In [ ]:
alt_a[0,1] = 25

In [ ]:
alt_a

array([[10, 25],
       [ 6,  6]])

In [ ]:
a

array([[10, 25,  4,  1,  6],
       [ 6,  6, 11,  0, 11],
       [ 6,  6, 12,  8, 11],
       [ 7, 12, 12, 10, 11],
       [10, 10,  6,  3,  5]])

In [ ]:
b = np.random.randint(15, size =(5,5))
b

array([[ 3, 11, 13, 13,  2],
       [ 8, 10,  4,  0,  1],
       [ 4,  4,  2,  5,  1],
       [13,  3, 13,  5, 10],
       [13, 14,  9,  0,  9]])

In [ ]:
alt_b = b[0:4, 0:5].copy()
alt_b

array([[ 3, 11, 13, 13,  2],
       [ 8, 10,  4,  0,  1],
       [ 4,  4,  2,  5,  1],
       [13,  3, 13,  5, 10]])

In [ ]:
alt_b[0,1] = 75
alt_b

array([[ 3, 75, 13, 13,  2],
       [ 8, 10,  4,  0,  1],
       [ 4,  4,  2,  5,  1],
       [13,  3, 13,  5, 10]])

In [ ]:
b

array([[ 3, 11, 13, 13,  2],
       [ 8, 10,  4,  0,  1],
       [ 4,  4,  2,  5,  1],
       [13,  3, 13,  5, 10],
       [13, 14,  9,  0,  9]])

In [ ]:
x = np.arange(5, 35, 5)
x

array([ 5, 10, 15, 20, 25, 30])

In [ ]:
x [4]

25

In [ ]:
[x[0], x[2], x[5]]

[5, 15, 30]

In [ ]:
y =[2,4,6]


**KOŞULLU ELEMAN**

In [ ]:
x > 4

array([ True,  True,  True,  True,  True,  True])

In [ ]:
x[x > 4]

array([ 5, 10, 15, 20, 25, 30])

In [ ]:
x * 3

array([15, 30, 45, 60, 75, 90])

In [ ]:
x ** 3

array([  125,  1000,  3375,  8000, 15625, 27000])

In [ ]:
np.subtract(x, 1)

array([ 4,  9, 14, 19, 24, 29])

In [ ]:
np.add(x,1)

array([ 6, 11, 16, 21, 26, 31])

In [ ]:
x.mean()

17.5

In [ ]:
x.sum()

105

In [ ]:
x.max()

30

**İKİ BİLİNMEYENLİ DENKLEM ÇÖZÜMÜ**

In [ ]:
a = np.array([[6,2], [2,5]])
b = np.array([8, 10])
x =np.linalg.solve(a,b)
x

array([0.76923077, 1.69230769])